####                        CLASS TASK FOUR

### Case Study: Student performance Analysis with Linear Algebra

1. Introduction 
In this case study, we will use Linear Algebra concepts (vectors, vector operations, matrices, 
and matrix operations) to analyze student performance data. 

Linear Algebra is powerful because it allows us to represent and manipulate data in a 
structured way. For example:

- Each student’s scores can be represented as a vector.

- A group of students’ scores across subjects can be represented as a matrix.
- We can then use vector and matrix operations to compute totals, averages, and weighted 
grades. 

2. Problem Setup 

We have the scores of 4 students in 3 subjects (Mathematics, English, Science):

Student        Math       English      Science
Student 1       80          70           90
Student 2       60          85           75
Student 3       95          88           92
Student 4       70          60           65

We will represent this dataset as a matrix:

[[80, 70, 90], 
[60, 85, 75], 
[95, 88, 92], 
[70, 60, 65]] 

3.1 Representing Data as a Matrix 

Represent the scores as a 4x3 matrix, where rows = students and columns = subjects. 

3.2 Total Scores per Student (Vector Addition) 
Compute the total score for each student by summing across the row vector. 

3.3 Applying Weights (Scalar Multiplication) 
Apply subject weights (e.g., Math is twice as important as others) using scalar 
multiplication. 

3.4 Average Score per Subject (Matrix Operations) 
Compute the average score for each subject by calculating the column-wise mean. 

3.5 Final Grades using Matrix Multiplication 
Use matrix multiplication with a weight vector (e.g., [0.5, 0.3, 0.2]) to calculate final grades. 

3.6 Comparing Students (Vector Subtraction) 
Compare two students’ performances by subtracting their score vectors. 

In [1]:
import numpy as np

# 3.1Represent the scores as  a 4x3 matrix, where rows=students and columns = subjects
student=np.array([[80, 70, 90], 
        [60, 85, 75], 
        [95, 88, 92], 
        [70, 60, 65]])
matrix_4x3=np.array(student)
print(student)


# 3.2 computing the total score for each student by summing across the row vector
student_1= [80 + 70 + 90]
print(f"Total sum for student_1:\n{student_1}")
student_2= [60 + 85 + 75]
print(f"Total sum for student_2:\n{student_2}")
student_3= [95 + 88 +  92]
print(f"Total sum for student_3:\n{student_3}")
student_4= [70 + 60 + 65]
print(f"Total sum for student_4:\n {student_4}")



    


[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]
Total sum for student_1:
[240]
Total sum for student_2:
[220]
Total sum for student_3:
[275]
Total sum for student_4:
 [195]


In [2]:
#3.3  Applying Weights (e.g math is twice as important as others) using scalar multiplication
scalar_weight_math = (2 * student[:, 0])

print(f"scalar weight for math:\n{scalar_weight_math}")

scalar_weight_english= (1 * student[:, 1])
print(f"scalar_weight_english:\n{scalar_weight_english}")
scalar_weight_science= (1* student[:, 2])
print(f"scalar_weight_science\n{scalar_weight_science}")




scalar weight for math:
[160 120 190 140]
scalar_weight_english:
[70 85 88 60]
scalar_weight_science
[90 75 92 65]


In [3]:
# 3.4 Average Score per Subject (Matrix Operations) 
# Compute the average score for each subject by calculating the column-wise mean.
Average_score_per_subject=np.mean(student, axis=0)
Average_score_per_subject

array([76.25, 75.75, 80.5 ])

In [4]:
# 3.5 Final Grades using Matrix Multiplication 
# Use matrix multiplication with a weight vector (e.g., [0.5, 0.3, 0.2]) to calculate final grades.
weight_vector=[0.4, 0.3, 0.3]
a= student.T
# print(a)
row1 = np.dot(weight_vector, student[0, :])
print(f"final_grade for row one:\n{row1}")
row2 = np.dot(weight_vector, student[1, :])
print(f"final_grade for row two:\n{row2}")
row3 = np.dot(weight_vector, student[2, :])
print(f"final_grade for row three:\n{row3}")
row4= np.dot(weight_vector, student[3, :])
print(f"final_grade for row three:\n {row4}")
 



final_grade for row one:
80.0
final_grade for row two:
72.0
final_grade for row three:
92.0
final_grade for row three:
 65.5


In [5]:
# 3.6 Comparing Students (Vector Subtraction) 
# Compare two students’ performances by subtracting their score vectors
compared_result1=np.subtract(student_1, student_2 )
print(f"This is the compared results of student_1 and student_2:\n{compared_result1}")
compared_result2=np.subtract(student_3, student_4)
print(f"This is the compared results of student_3 and student_4:\n{compared_result2}")

This is the compared results of student_1 and student_2:
[20]
This is the compared results of student_3 and student_4:
[80]


4. Key Takeaways - Vectors represent individual students’ scores. 

- Vector addition/subtraction helps compare performance. 
- Scalar multiplication applies importance/weights to subjects.
 - Matrices represent the whole dataset. 
- Matrix multiplication is used for weighted grading. 

5. Add-on Exercises  
1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total 
score and the average per subject. 
2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar 
multiplication and recompute totals. 
3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using 
matrix multiplication. 
4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each subjects?

In [6]:
1#. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total 
# score and the average per subject. 
scores=np.random.randint(1, 91, size=(5, 4))
print(scores)
# Compute each student's total score
for i, row in enumerate(scores):
    total_score = np.sum(scores, axis=1)
    print(f"The total score: {i + 1} is {scores}")

# To compute average score per subjects
for i, column_index in enumerate(range(scores.shape[1])):
    Average_score_per_subject=np.average(scores[:, column_index])
    subjects=["Math","English", "Science", "Yoruba"]
    print(f"The average scores of {subjects[i]} is {Average_score_per_subject} ")
 




[[ 4 70 63 71]
 [ 3 27 61 83]
 [73 87 35 45]
 [59 33  9 64]
 [39 28 35 64]]
The total score: 1 is [[ 4 70 63 71]
 [ 3 27 61 83]
 [73 87 35 45]
 [59 33  9 64]
 [39 28 35 64]]
The total score: 2 is [[ 4 70 63 71]
 [ 3 27 61 83]
 [73 87 35 45]
 [59 33  9 64]
 [39 28 35 64]]
The total score: 3 is [[ 4 70 63 71]
 [ 3 27 61 83]
 [73 87 35 45]
 [59 33  9 64]
 [39 28 35 64]]
The total score: 4 is [[ 4 70 63 71]
 [ 3 27 61 83]
 [73 87 35 45]
 [59 33  9 64]
 [39 28 35 64]]
The total score: 5 is [[ 4 70 63 71]
 [ 3 27 61 83]
 [73 87 35 45]
 [59 33  9 64]
 [39 28 35 64]]
The average scores of Math is 35.6 
The average scores of English is 49.0 
The average scores of Science is 40.6 
The average scores of Yoruba is 65.4 


In [7]:
scores= np.random.randint(1,91, size=(5,4))
print(scores)

subjects=["eng", "math", "yoruba", "french"]


# computing data
for i, row in enumerate(scores):
    total_score=scores[i,:].sum()
    print(f"The total scores{i + 1} is {total_score}")

# compute average scores
for i, column_index in enumerate(range (scores.shape[1])):
    Average_score_per_subject=np.average(scores[:, column_index])    
    print(f"The average scores {subjects[i]} is {Average_score_per_subject}")
    
    
    


[[63 57 82  8]
 [79 40 52 48]
 [69  3 28  2]
 [50 30 43 49]
 [ 9 35 23 75]]
The total scores1 is 210
The total scores2 is 219
The total scores3 is 102
The total scores4 is 172
The total scores5 is 142
The average scores eng is 54.0
The average scores math is 33.0
The average scores yoruba is 45.6
The average scores french is 36.4


In [8]:
#2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar 
# multiplication and recompute totals

scalar_weight= [3, 1, 1, 1]
zeros_matrix=np.zeros_like(scores)
print(zeros_matrix)
for i, row in enumerate(scores):
    zeros_matrix[i, :]=scores[i,:] * scalar_weight
    scaled_score=scores[i,:] * scalar_weight
    print(f"The scaled scores{i + 1} is {scaled_score}")
print(zeros_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
The scaled scores1 is [189  57  82   8]
The scaled scores2 is [237  40  52  48]
The scaled scores3 is [207   3  28   2]
The scaled scores4 is [150  30  43  49]
The scaled scores5 is [27 35 23 75]
[[189  57  82   8]
 [237  40  52  48]
 [207   3  28   2]
 [150  30  43  49]
 [ 27  35  23  75]]


### 3.  Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using matrix multiplicaton

In [9]:
weight_vector=( 0.4, 0.2, 0.3, 0.1)
np.dot(scores, weight_vector)

array([62. , 60. , 36.8, 43.8, 25. ])

In [10]:

# # 4.compare Student 3 and Student 4 using vector subtraction. Who performed better in each subjects?
compared_result=np.subtract(scores[2, :], scores[3, :])
print(compared_result)

student3 = scores[2, :]
student4 = scores[3, :]




# 
#         for i, column in enumerate(student3, student_4):
#                 print(f'Student 3 performed better than Student 4 in {subjects[i]} subject scoring {column}.')
# else:
#         print('Student 4 performed better than Student 3')
# result = np.subtract(student3, student4)
# subjects = ['English', 'Maths', 'Yoruba', 'French']
# for i, column in enumerate(result):
#     if student_3 > student_4:
#         print(f'Student 3 performed better than Student 4 in {subjects[i]} by{result[column]} marks')


[ 19 -27 -15 -47]


In [11]:
subjects = ["English", 'Maths', 'Yoruba', 'French']
if student_3 > student_4:
    for i in subjects:
        print(f'Student 3 performed better than Student 4 in {i} by {compared_result} marks')


Student 3 performed better than Student 4 in English by [ 19 -27 -15 -47] marks
Student 3 performed better than Student 4 in Maths by [ 19 -27 -15 -47] marks
Student 3 performed better than Student 4 in Yoruba by [ 19 -27 -15 -47] marks
Student 3 performed better than Student 4 in French by [ 19 -27 -15 -47] marks
