In [5]:
import numpy as np
#1. create a 6x6 Numpy array with integers between 1 and 50
arrays_num = np.random.randint(50, size=(6,6))
print(arrays_num)

[[ 6 32 39  6  1  0]
 [44 41 11  9 37 45]
 [45  6 47 46 33 35]
 [37 38 34 28 12  1]
 [37 29 18 39 39 14]
 [43 13 48 39 48  0]]


In [ ]:
#2. Extract the following from the array you created in Question 1: 
# The first two rows.The last three columns.
# All even numbers in the array.

first_row=arrays_num[0:2, :]
print(f"first_row:\n{first_row}")
second_col= arrays_num[:-3, :]
print(f"second_row; {second_col}")
even_num = arrays_num[arrays_num % 2 ==0 ]
print(even_num)

first_row:
[[ 6 32 39  6  1  0]
 [44 41 11  9 37 45]]
second_row; [[ 6 32 39  6  1  0]
 [44 41 11  9 37 45]
 [45  6 47 46 33 35]]
[ 6 32  6  0 44  6 46 38 34 28 12 18 14 48 48  0]
