In [1]:
import numpy as np
#1. create a 6x6 Numpy array with integers between 1 and 50
arrays_num = np.random.randint(50, size=(6,6))
print(arrays_num)

[[ 2 34 26 49 22 43]
 [29 18 23 29 28 32]
 [ 4  4 15 16 29  5]
 [ 4  6 21  0 46 22]
 [ 9 36 45 17 26  6]
 [41 15 16  4 49  8]]


In [59]:
#2. Extract the following from the array you created in Question 1: 
# The first two rows.The last three columns.
# All even numbers in the array

first_two_rows = arrays_num [0:2,0:6]
print(f"first_two_rows; {first_two_rows}")

last_three_columns = arrays_num[0:6,3:6]
print(f"last_three_column: {last_three_columns} ")

even_num = arrays_num[arrays_num % 2 ==0 ]
print(even_num)

first_two_rows; [[10 24 28 28 41 39]
 [22 33 37 49 21 28]]
last_three_column: [[28 41 39]
 [49 21 28]
 [20 16 36]
 [11  2 23]
 [22 17 47]
 [19 20 33]] 
[10 24 28 28 22 28 26 36 20 16 36  4  2 22 22 12  2 20]


In [60]:
# 3. Perform the following array transformations:
# Reshape the array into 3D (3, 2, 6)
reshaped_3d= arrays_num.reshape(3, 2,6)
print(f"Reshaped to 3x2x6;\n", [reshaped_3d])

# Flattened the reshape array back to 1D
flattened= arrays_num.flatten()
print(f"flattened(copy):", flattened)


Reshaped to 3x2x6;
 [array([[[10, 24, 28, 28, 41, 39],
        [22, 33, 37, 49, 21, 28]],

       [[25, 26, 36, 20, 16, 36],
        [ 4, 33, 31, 11,  2, 23]],

       [[25, 39, 22, 22, 17, 47],
        [43, 12,  2, 19, 20, 33]]], dtype=int32)]
flattened(copy): [10 24 28 28 41 39 22 33 37 49 21 28 25 26 36 20 16 36  4 33 31 11  2 23
 25 39 22 22 17 47 43 12  2 19 20 33]


In [61]:
# 4. diagonal identification of matrix and replacing  the diagonal with numbers from 10 to 40

matrix_identity= np.eye(4)
print(matrix_identity)
number= np.array([10, 20, 30, 40])
np.fill_diagonal(matrix_identity, number)
print("\n", matrix_identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 [[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


In [62]:
# 5. perform matrix multiplication between: A 3x4 matrix of random integers(1-10) A 4x3 matrix of random integers (1-10)\n"
matrix_3x4= np.random.randint(1, 11,  size=(3, 4)) 
print(matrix_3x4)
matrix_4x3= np.random.randint(1,11, size=(4,3))
print(matrix_4x3)
outcome= np.dot(matrix_3x4, matrix_4x3)
print(outcome)

[[ 3 10  4  4]
 [ 3  3  2  5]
 [ 4  9  1  5]]
[[ 4 10  3]
 [ 7 10  7]
 [10  6 10]
 [ 7  8  9]]
[[150 186 155]
 [ 88 112  95]
 [124 176 130]]


In [79]:
# 6. create a function that takes a 2D Numpy array as input and returns a new array where: All even numbers are squared.
# All odd numbers are replaced by -1
def generatte_array(arrays_num):
    arrays_num= np.where(arrays_num% 2 == 0,arrays_num**2, -1)
    print(f"{arrays_num}")
generatte_array(arrays_num)    


[[ 100  576  784  784   -1   -1]
 [ 484   -1   -1   -1   -1  784]
 [  -1  676 1296  400  256 1296]
 [  16   -1   -1   -1    4   -1]
 [  -1   -1  484  484   -1   -1]
 [  -1  144    4   -1  400   -1]]
