In [1]:
import numpy as np
#1. create a 6x6 Numpy array with integers between 1 and 50
arrays_num = np.random.randint(50, size=(6,6))
print(arrays_num)

[[14  5 39 42 42 43]
 [ 1  5 25 15 11  8]
 [40  5 41 33 44 49]
 [27 46  6 27 33 25]
 [22 34 23  8 22 30]
 [28 26 29 24 16  5]]


In [2]:
#2. Extract the following from the array you created in Question 1: 
# The first two rows.The last three columns.
# All even numbers in the array

first_two_rows = arrays_num [0:2,0:6]
print(f"first_two_rows; {first_two_rows}")

last_three_columns = arrays_num[0:6,3:6]
print(f"last_three_column: {last_three_columns} ")

even_num = arrays_num[arrays_num % 2 ==0 ]
print(even_num)

first_two_rows; [[14  5 39 42 42 43]
 [ 1  5 25 15 11  8]]
last_three_column: [[42 42 43]
 [15 11  8]
 [33 44 49]
 [27 33 25]
 [ 8 22 30]
 [24 16  5]] 
[14 42 42  8 40 44 46  6 22 34  8 22 30 28 26 24 16]


In [3]:
# 3. Perform the following array transformations:
# Reshape the array into 3D (3, 2, 6)
reshaped_3d= arrays_num.reshape(3, 2,6)
print(f"Reshaped to 3x2x6:\n", [reshaped_3d])

# Flattened the reshape array back to 1D
flattened= arrays_num.flatten()
print(f"flattened(copy):", flattened)


Reshaped to 3x2x6:
 [array([[[14,  5, 39, 42, 42, 43],
        [ 1,  5, 25, 15, 11,  8]],

       [[40,  5, 41, 33, 44, 49],
        [27, 46,  6, 27, 33, 25]],

       [[22, 34, 23,  8, 22, 30],
        [28, 26, 29, 24, 16,  5]]], dtype=int32)]
flattened(copy): [14  5 39 42 42 43  1  5 25 15 11  8 40  5 41 33 44 49 27 46  6 27 33 25
 22 34 23  8 22 30 28 26 29 24 16  5]


In [ ]:
# 4. diagonal identification of matrix and replacing  the diagonal with numbers from 10 to 40

matrix_identity= np.eye(4)
print(matrix_identity)
number= np.array([10, 20, 30, 40])
np.fill_diagonal(matrix_identity, number)
print("\n", matrix_identity)

# Or
dia=np.diag([10, 20, 30, 40])
print(dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 [[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [5]:
# 5. perform matrix multiplication between: A 3x4 matrix of random integers(1-10) A 4x3 matrix of random integers (1-10)\n"
matrix_3x4= np.random.randint(1, 11,  size=(3, 4)) 
print(matrix_3x4)
matrix_4x3= np.random.randint(1,11, size=(4,3))
print(matrix_4x3)
outcome= np.dot(matrix_3x4, matrix_4x3)
print(outcome)

[[ 6  5 10  7]
 [ 2  5  6  9]
 [ 2  5 10  5]]
[[ 9  3  7]
 [ 8  1  2]
 [ 8  4  4]
 [ 1  2 10]]
[[181  77 162]
 [115  53 138]
 [143  61 114]]


In [6]:
# 6. create a function that takes a 2D Numpy array as input and returns a new array where: All even numbers are squared.
# All odd numbers are replaced by -1
def generatte_array(arrays_num):
    arrays_num= np.where(arrays_num% 2 == 0,arrays_num**2, -1)
    print(f"{arrays_num}")
generatte_array(arrays_num)    


[[ 196   -1   -1 1764 1764   -1]
 [  -1   -1   -1   -1   -1   64]
 [1600   -1   -1   -1 1936   -1]
 [  -1 2116   36   -1   -1   -1]
 [ 484 1156   -1   64  484  900]
 [ 784  676   -1  576  256   -1]]
