In [1]:
import numpy as np
#1. create a 6x6 Numpy array with integers between 1 and 50
arrays_num = np.random.randint(50, size=(6,6))
print(arrays_num)

[[17  1 10 40  3 14]
 [10  2 16 26  1  1]
 [39 19 13 48 33 18]
 [22 35 18 38 18 21]
 [22  3 29 30 46 25]
 [25 46 16 36  0  8]]


In [2]:
#2. Extract the following from the array you created in Question 1: 
# The first two rows.The last three columns.
# All even numbers in the array

first_two_rows = arrays_num [0:2,0:6]
print(f"first_two_rows; {first_two_rows}")

last_three_columns = arrays_num[0:6,3:6]
print(f"last_three_column: {last_three_columns} ")

even_num = arrays_num[arrays_num % 2 ==0 ]
print(even_num)

first_two_rows; [[17  1 10 40  3 14]
 [10  2 16 26  1  1]]
last_three_column: [[40  3 14]
 [26  1  1]
 [48 33 18]
 [38 18 21]
 [30 46 25]
 [36  0  8]] 
[10 40 14 10  2 16 26 48 18 22 18 38 18 22 30 46 46 16 36  0  8]


In [3]:
# 3. Perform the following array transformations:
# Reshape the array into 3D (3, 2, 6)
reshaped_3d= arrays_num.reshape(3, 2,6)
print(f"Reshaped to 3x2x6:\n", [reshaped_3d])

# Flattened the reshape array back to 1D
flattened= arrays_num.flatten()
print(f"flattened(copy):", flattened)


Reshaped to 3x2x6:
 [array([[[17,  1, 10, 40,  3, 14],
        [10,  2, 16, 26,  1,  1]],

       [[39, 19, 13, 48, 33, 18],
        [22, 35, 18, 38, 18, 21]],

       [[22,  3, 29, 30, 46, 25],
        [25, 46, 16, 36,  0,  8]]], dtype=int32)]
flattened(copy): [17  1 10 40  3 14 10  2 16 26  1  1 39 19 13 48 33 18 22 35 18 38 18 21
 22  3 29 30 46 25 25 46 16 36  0  8]


In [4]:
# 4. diagonal identification of matrix and replacing  the diagonal with numbers from 10 to 40

matrix_identity= np.eye(4)
print(matrix_identity)
number= np.array([10, 20, 30, 40])
np.fill_diagonal(matrix_identity, number)
print("\n", matrix_identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 [[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


In [5]:
# 5. perform matrix multiplication between: A 3x4 matrix of random integers(1-10) A 4x3 matrix of random integers (1-10)\n"
matrix_3x4= np.random.randint(1, 11,  size=(3, 4)) 
print(matrix_3x4)
matrix_4x3= np.random.randint(1,11, size=(4,3))
print(matrix_4x3)
outcome= np.dot(matrix_3x4, matrix_4x3)
print(outcome)

[[ 4  5  2  9]
 [ 7  1  1  1]
 [ 2  1 10 10]]
[[ 6  3 10]
 [ 7  9  6]
 [ 3  6  2]
 [ 5  8 10]]
[[110 141 164]
 [ 57  44  88]
 [ 99 155 146]]


In [6]:
# 6. create a function that takes a 2D Numpy array as input and returns a new array where: All even numbers are squared.
# All odd numbers are replaced by -1
def generatte_array(arrays_num):
    arrays_num= np.where(arrays_num% 2 == 0,arrays_num**2, -1)
    print(f"{arrays_num}")
generatte_array(arrays_num)    


[[  -1   -1  100 1600   -1  196]
 [ 100    4  256  676   -1   -1]
 [  -1   -1   -1 2304   -1  324]
 [ 484   -1  324 1444  324   -1]
 [ 484   -1   -1  900 2116   -1]
 [  -1 2116  256 1296    0   64]]
