In [22]:
import numpy as np



In [23]:
matrix_identity= np.eye(4)
print(matrix_identity)
number=np.array([10, 20, 30, 40])
np.fill_diagonal(matrix_identity, number)
print(matrix_identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


In [24]:
matrix_3x4= np.random.randint(1, 11,  size=(3,4))
print(matrix_3x4)
matrix_4x3= np.random.randint(1, 11, size=(4,3))
print(matrix_4x3)
outcome=np.dot(matrix_4x3, matrix_3x4)
print(outcome)

[[3 3 3 4]
 [9 4 8 7]
 [9 9 9 2]]
[[ 9  3 10]
 [ 2 10  1]
 [ 9  6  2]
 [ 3  6  6]]
[[144 129 141  77]
 [105  55  95  80]
 [ 99  69  93  82]
 [117  87 111  66]]


In [ ]:
def generatte_array(array_nums):
    array_nums= np.where(array_nums% 2 == 0,array_nums**2, -1 )
    print(f"{array_nums}")
generatte_array(array_nums)   