In [65]:
# import all neccessary libraries
import numpy as np
import matplotlib.pyplot as plt
import time

In [66]:
# To check Numpy version
print(f"Numpy version: {np.__version__}") 

Numpy version: 2.3.3


In [67]:
# creating a numpy arrays
# creating array from python lists
# array: A simple sequences of numbers 
arrd1 = np.array([1, 2, 3, 4, 5])

arrd2 = np.array([[1, 2, 3],
               [4, 5, 6]])
arrd3 = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

In [68]:
# creating 1D, 2D and 3D array
arrd1=np.array([1, 2, 3, 4, 5, 6])

arrd2=np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [ ]:
import numpy as np
arr= np.random.randint(50, size=[6, 6])
print(arr)

[[18 42 11 47  3 21]
 [30 46 13 23 40 49]
 [20  9 20 30  7 22]
 [ 7 27 26 42 24 36]
 [16 14 27 35 16 10]
 [ 8 48  2 41  1 18]]


In [ ]:
# the first two and the last three columns
# all even numbers
# first_two_rows=arr[0:3]
# print(first_two_rows)
last_c=arr[0:2, 0:6]
print(last_c)
last_b=arr[0:6, 3:6]
print(last_b)


[[13 15 24 43 12 42]
 [46 26 39 27 38 11]]
[[43 12 42]
 [27 38 11]
 [32 17 45]
 [31 32 22]
 [26 44 21]
 [ 8 40  2]]


In [ ]:
evens=arr[arr % 2 ==0]
print(evens)

[24 12 42 46 26 38 14 14 32 18  0 32 22 26 44 22 46  0  8 40  2]


In [ ]:
reshaped=arr.reshape(3, 2, 6)
print(reshaped)
flat=arr.flatten()
print(flat)

[[[13 15 24 43 12 42]
  [46 26 39 27 38 11]]

 [[14 25 14 32 17 45]
  [15 18  0 31 32 22]]

 [[29  9 21 26 44 21]
  [22 46  0  8 40  2]]]
[13 15 24 43 12 42 46 26 39 27 38 11 14 25 14 32 17 45 15 18  0 31 32 22
 29  9 21 26 44 21 22 46  0  8 40  2]


In [ ]:
matrix_identity=np.eye(4)
print(matrix_identity)
dia=np.diag([10, 20, 30, 40])
print(dia)
full=np.full((3, 4), 6)
print(full)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [ ]:
def generatte_array(arr):
    arr=np.where(arr % 2 ==0,arr**2, -1)
    print(f"{arr}")
generatte_array(arr) 

[[ 324 1764   -1   -1   -1   -1]
 [ 900 2116   -1   -1 1600   -1]
 [ 400   -1  400  900   -1  484]
 [  -1   -1  676 1764  576 1296]
 [ 256  196   -1   -1  256  100]
 [  64 2304    4   -1   -1  324]]


In [ ]:
# 6. create a function that takes a 2D Numpy array as input and returns a new array where: All even numbers are squared.
# All odd numbers are replaced by -1
import numpy as np
def generate_array(arr):
    arr=np.where(arr % 2 ==0, arr**2, -1)
    print(arr)
generate_array(arr)    
    
# 4. diagonal identification of matrix and replacing  the diagonal with numbers from 10 to 40
matrix=np.eye(4)
print(matrix)
dia=np.diag([10, 20, 30, 40])
print(dia)

[[ 324 1764   -1   -1   -1   -1]
 [ 900 2116   -1   -1 1600   -1]
 [ 400   -1  400  900   -1  484]
 [  -1   -1  676 1764  576 1296]
 [ 256  196   -1   -1  256  100]
 [  64 2304    4   -1   -1  324]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [82]:
# 3. Perform the following array transformations:
# Reshape the array into 3D (3, 2, 6)
reshaped=matrix.reshape(3,2, 6)
print(reshaped)
flat=matrix.flatten()
print(flat)


[[[40 33  8  7 21  5]
  [16 19 48 38 31  1]]

 [[19 12 26 16 45  8]
  [ 1 47 17 19 37 23]]

 [[18 13 28 23 16  8]
  [16 10 15 45 11 19]]]
[40 33  8  7 21  5 16 19 48 38 31  1 19 12 26 16 45  8  1 47 17 19 37 23
 18 13 28 23 16  8 16 10 15 45 11 19]


In [ ]:
#2. Extract the following from the array you created in Question 1: 
# The first two rows.The last three columns.
# All even numbers in the array

In [80]:
# 5. perform matrix multiplication between: A 3x4 matrix of random integers(1-10) A 4x3#1. create a 6x6 Numpy array with integers between 1 and 50
matrix_3x4= np.random.randint(1, 10, size=(3, 4))
print(matrix_3x4)
matrix_4x3=np.random.randint(1, 10, size=(4, 3))
print(matrix_4x3)
all=np.dot(matrix_4x3, matrix_3x4)
print(all)

#1. create a 6x6 Numpy array with integers between 1 and 50
import numpy as np
matrix=np.random.randint(50, size=(6, 6))
print(matrix)

first_2_row=matrix[0:2, 0:6]
print(first_2_row)
last=matrix[0:6, 3:6]
print(last)
evenss=matrix[matrix % 2 ==0]
print(evenss)

[[7 7 5 6]
 [7 4 1 8]
 [8 6 9 7]]
[[5 4 4]
 [8 5 2]
 [4 4 7]
 [2 8 2]]
[[ 95  75  65  90]
 [107  88  63 102]
 [112  86  87 105]
 [ 86  58  36  90]]
[[40 33  8  7 21  5]
 [16 19 48 38 31  1]
 [19 12 26 16 45  8]
 [ 1 47 17 19 37 23]
 [18 13 28 23 16  8]
 [16 10 15 45 11 19]]
[[40 33  8  7 21  5]
 [16 19 48 38 31  1]]
[[ 7 21  5]
 [38 31  1]
 [16 45  8]
 [19 37 23]
 [23 16  8]
 [45 11 19]]
[40  8 16 48 38 12 26 16  8 18 28 16  8 16 10]
