####                        CLASS TASK FOUR

### Case Study: Student performance Analysis with Linear Algebra

1. Introduction 
In this case study, we will use Linear Algebra concepts (vectors, vector operations, matrices, 
and matrix operations) to analyze student performance data. 

Linear Algebra is powerful because it allows us to represent and manipulate data in a 
structured way. For example:

- Each student’s scores can be represented as a vector.

- A group of students’ scores across subjects can be represented as a matrix.
- We can then use vector and matrix operations to compute totals, averages, and weighted 
grades. 

2. Problem Setup 

We have the scores of 4 students in 3 subjects (Mathematics, English, Science):

Student        Math       English      Science
Student 1       80          70           90
Student 2       60          85           75
Student 3       95          88           92
Student 4       70          60           65

We will represent this dataset as a matrix:

[[80, 70, 90], 
[60, 85, 75], 
[95, 88, 92], 
[70, 60, 65]] 

3.1 Representing Data as a Matrix 

Represent the scores as a 4x3 matrix, where rows = students and columns = subjects. 

3.2 Total Scores per Student (Vector Addition) 
Compute the total score for each student by summing across the row vector. 

3.3 Applying Weights (Scalar Multiplication) 
Apply subject weights (e.g., Math is twice as important as others) using scalar 
multiplication. 

3.4 Average Score per Subject (Matrix Operations) 
Compute the average score for each subject by calculating the column-wise mean. 

3.5 Final Grades using Matrix Multiplication 
Use matrix multiplication with a weight vector (e.g., [0.5, 0.3, 0.2]) to calculate final grades. 

3.6 Comparing Students (Vector Subtraction) 
Compare two students’ performances by subtracting their score vectors. 

In [36]:
import numpy as np

# 3.1Represent the scores as  a 4x3 matrix, where rows=students and columns = subjects
student=np.array([[80, 70, 90], 
        [60, 85, 75], 
        [95, 88, 92], 
        [70, 60, 65]])
matrix_4x3=np.array(student)
print(student)


# 3.2 computing the total score for each student by summing across the row vector
student_1= [80 + 70 + 90]
print(f"Total sum for student_1:\n{student_1}")
student_2= [60 + 85 + 75]
print(f"Total sum for student_2:\n{student_2}")
student_3= [95 + 88 +  92]
print(f"Total sum for student_3:\n{student_3}")
student_4= [70 + 60 + 65]
print(f"Total sum for student_4:\n {student_4}")



    


[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]
Total sum for student_1:
[240]
Total sum for student_2:
[220]
Total sum for student_3:
[275]
Total sum for student_4:
 [195]


In [37]:
#3.3  Applying Weights (e.g math is twice as important as others) using scalar multiplication
scalar_weight_math = (2 * student[:, 0])

print(f"scalar weight for math:\n{scalar_weight_math}")

scalar_weight_english= (1 * student[:, 1])
print(f"scalar_weight_english:\n{scalar_weight_english}")
scalar_weight_science= (1* student[:, 2])
print(f"scalar_weight_science\n{scalar_weight_science}")




scalar weight for math:
[160 120 190 140]
scalar_weight_english:
[70 85 88 60]
scalar_weight_science
[90 75 92 65]


In [38]:
# 3.4 Average Score per Subject (Matrix Operations) 
# Compute the average score for each subject by calculating the column-wise mean.
Average_score_per_subject=np.mean(student, axis=0)
Average_score_per_subject

array([76.25, 75.75, 80.5 ])

In [39]:
# 3.5 Final Grades using Matrix Multiplication 
# Use matrix multiplication with a weight vector (e.g., [0.5, 0.3, 0.2]) to calculate final grades.
weight_vector=[0.4, 0.3, 0.3]
a= student.T
# print(a)
row1 = np.dot(weight_vector, student[0, :])
print(f"final_grade for row one:\n{row1}")
row2 = np.dot(weight_vector, student[1, :])
print(f"final_grade for row two:\n{row2}")
row3 = np.dot(weight_vector, student[2, :])
print(f"final_grade for row three:\n{row3}")
row4= np.dot(weight_vector, student[3, :])
print(f"final_grade for row three:\n {row4}")




final_grade for row one:
80.0
final_grade for row two:
72.0
final_grade for row three:
92.0
final_grade for row three:
 65.5


In [40]:
# 3.6 Comparing Students (Vector Subtraction) 
# Compare two students’ performances by subtracting their score vectors
compared_result1=np.subtract(student_1, student_2 )
print(f"This is the compared results of two students:\n{compared_result1}")
compared_result2=np.subtract(student_3, student_4)
print(f"This is the compared resulits of another two students:\n{compared_result2}")

This is the compared results of two students:
[20]
This is the compared resulits of another two students:
[80]


4. Key Takeaways - Vectors represent individual students’ scores. 

- Vector addition/subtraction helps compare performance. 
- Scalar multiplication applies importance/weights to subjects.
 - Matrices represent the whole dataset. 
- Matrix multiplication is used for weighted grading. 

5. Add-on Exercises  
1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total 
score and the average per subject. 
2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar 
multiplication and recompute totals. 
3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using 
matrix multiplication. 
4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each subjects?

In [41]:
1#. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total 
# score and the average per subject. 
scores=np.random.randint(1, 91, size=(5, 4))
print(scores)
# Compute each student's total score
for i, row in enumerate(scores):
    total_score = np.sum(scores, axis=1)
    print(f"The total score: {i + 1} is {scores}")

# To compute average score per subjects
for i, column_index in enumerate(range(scores.shape[1])):
    Average_score_per_subject=np.average(scores[:, column_index])
    subjects=["Math","English", "Science", "Yoruba"]
    print(f"The average scores of {subjects[i]} is {Average_score_per_subject} ")
 




[[45 44 28 76]
 [28 14 10 37]
 [ 2 72 59 83]
 [70 49 89 61]
 [33 36 12 22]]
The total score: 1 is [[45 44 28 76]
 [28 14 10 37]
 [ 2 72 59 83]
 [70 49 89 61]
 [33 36 12 22]]
The total score: 2 is [[45 44 28 76]
 [28 14 10 37]
 [ 2 72 59 83]
 [70 49 89 61]
 [33 36 12 22]]
The total score: 3 is [[45 44 28 76]
 [28 14 10 37]
 [ 2 72 59 83]
 [70 49 89 61]
 [33 36 12 22]]
The total score: 4 is [[45 44 28 76]
 [28 14 10 37]
 [ 2 72 59 83]
 [70 49 89 61]
 [33 36 12 22]]
The total score: 5 is [[45 44 28 76]
 [28 14 10 37]
 [ 2 72 59 83]
 [70 49 89 61]
 [33 36 12 22]]
The average scores of Math is 35.6 
The average scores of English is 43.0 
The average scores of Science is 39.6 
The average scores of Yoruba is 55.8 


In [50]:
scores= np.random.randint(1,91, size=(5,4))
print(scores)

subjects=["eng", "math", "yoruba", "french"]


# computing data
for i, row in enumerate(scores):
    total_score=scores[i,:].sum()
    print(f"The total scores{i + 1} is {total_score}")

# compute average scores
for i, column_index in enumerate(range (scores.shape[1])):
    Average_score_per_subject=np.average(scores[:, column_index])    
    print(f"The average scores {subjects[i]} is {Average_score_per_subject}")
    
    
    


[[77  4  1 67]
 [20 63 58 69]
 [35 66 26 39]
 [32 19 59 70]
 [30 80 81 18]]
The total scores1 is 149
The total scores2 is 210
The total scores3 is 166
The total scores4 is 180
The total scores5 is 209
The average scores eng is 38.8
The average scores math is 46.4
The average scores yoruba is 45.0
The average scores french is 52.6


In [ ]:
#2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar 
# multiplication and recompute totals

scalar_weight= [3, 1, 1, 1]
zeros_matrix=np.zeros_like(scores)
print(zeros_matrix)
for i, row in enumerate(scores):
    zeros_matrix[i, :]=scores[i,:] * scalar_weight
    scaled_score=scores[i,:] * scalar_weight
    print(f"The scaled scores{i + 1} is {scaled_score}")
print(zeros_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
The scaled scores1 is [231   4   1  67]
The scaled scores2 is [60 63 58 69]
The scaled scores3 is [105  66  26  39]
The scaled scores4 is [96 19 59 70]
The scaled scores5 is [90 80 81 18]
[[231   4   1  67]
 [ 60  63  58  69]
 [105  66  26  39]
 [ 96  19  59  70]
 [ 90  80  81  18]]


### 3.  Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using matrix multiplicaton