                   # TASK 3
 Let A= [2, -1], [0, 3],  B= [1, 4], [-2, 5]
    and let the scalars (c = 2), (d = 3).

(a) compute the following: (cA), (dB), and (c + d)A

(b) using the results gotten, verify the scalar Multiplication properties

 (c) Find the transpose of both matrices:

(d) check if (A) and (B) are invertible by computing thier derterminants. if they are invertible, find A^-1 and B^-1

In [22]:
# import all necessary libraries
import numpy as np
import matplotlib.pyplot as plt




In [23]:
#  compute the following : (cA), (dA), and (c + d)A
# Answer to question (a)

A= np.array([[2, -1], 
             [0, 3]])
B= np.array([[1, 4], [-2, 5]])

c = 2
d = 3

cA = (c * A)
print(cA)

dB=np.dot(d, B)
print(dB)

e = (c + d)
print(e * A)


[[ 4 -2]
 [ 0  6]]
[[ 3 12]
 [-6 15]]
[[10 -5]
 [ 0 15]]


In [29]:
transs_A= A.T
transs_b = B.transpose()
print(f"Transpose A:\n {transs_A} \nand Transpose B:\n {transs_b}")

Transpose A:
 [[ 2  0]
 [-1  3]] 
and Transpose B:
 [[ 1 -2]
 [ 4  5]]


In [ ]:
# check if (A) and (B) are invertible by computing thier derterminants. if they are invertible, find A^-1 and B^-1

In [38]:
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
print(det_A,det_B)

det_T = np.linalg.det(transs_A)
print(det_T)

print(np.linalg.inv(A))


print(np.linalg.inv(B))


6.0 13.0
6.0
[[0.5        0.16666667]
 [0.         0.33333333]]
[[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
