In [11]:
# 5. Add-on Exercises  
# 1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total
import numpy as np
 
# score and the average per subject. 
# 2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar 
# multiplication and recompute totals. 
# 3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using 
# matrix multiplication. 
# 4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each subjects?

# 3.1 Representing Data as a Matrix 

# Represent the scores as a 4x3 matrix, where rows = students and columns = subjects. 

# 3.2 Total Scores per Student (Vector Addition) 
# Compute the total score for each student by summing across the row vector. 

# 3.3 Applying Weights (Scalar Multiplication) 
# Apply subject weights (e.g., Math is twice as important as others) using scalar 
# multiplication. 

# 3.4 Average Score per Subject (Matrix Operations) 
# Compute the average score for each subject by calculating the column-wise mean. 

# 3.5 Final Grades using Matrix Multiplication 
# Use matrix multiplication with a weight vector (e.g., [0.5, 0.3, 0.2]) to calculate final grades. 

# 3.6 Comparing Students (Vector Subtraction) 
# Compare two students’ performances by subtracting their score vectors. 

In [38]:
import numpy as np
# 1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total
scores=np.random.randint(5, 20, size=(5,4))
print(scores)
# compute each student's total
for i, row in enumerate(scores):
    total_score=np.sum(scores, axis=1)
    print(f"This is the total score for the students {i + 1} is {total_score}")
# To compute the average score per subject
for i, column_index in enumerate(range(scores.shape[1])):
    average_score_per_subject=np.average(scores [:, column_index])
    subjects=["eng", "math", "ict", "crs"]    
    print(f"This is the average score of students in {subjects[i]}, is {average_score_per_subject}")

[[18 19 14  5]
 [11 10 15 10]
 [11 13  7 10]
 [ 6 11  8  7]
 [ 7  7 13 14]]
This is the total score for the students 1 is [56 46 41 32 41]
This is the total score for the students 2 is [56 46 41 32 41]
This is the total score for the students 3 is [56 46 41 32 41]
This is the total score for the students 4 is [56 46 41 32 41]
This is the total score for the students 5 is [56 46 41 32 41]
This is the average score of students in eng, is 10.6
This is the average score of students in math, is 12.0
This is the average score of students in ict, is 11.4
This is the average score of students in crs, is 9.2


In [ ]:
# 2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar 
# multiplication and recompute totals. 
scalar_mult=[3,1,1,1]
for i, row in enumerate(scores):
    scaled_score=scores[i, :] * scalar_mult

    print(f"The scaled score is {i + 1} in:\n{scaled_score}")






The scaled score is 1 in:
[54  8 10 12]
The scaled score is 2 in:
[27  8 15  7]
The scaled score is 3 in:
[57 14  7  9]
The scaled score is 4 in:
[21 18 13  7]
The scaled score is 5 in:
[33  8 18 18]


In [14]:
# 3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using 
# matrix multiplication.
new_weight=[0.4, 0.2, 0.3, 0.1] 
final_grade=np.dot(scores , new_weight)
print(final_grade)


# 4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each subjects?
print(scores)
student3=(scores[2,:])
print(student3)
student4=(scores[3,:])
print(student4)
subjects=("math", "eng", "crs", "yoruba")
for i, row in enumerate(scores):
    compared_result=np.subtract(student3, student4)
print(f"This is the result from{subjects, i} that was compared from student3 and student4{compared_result}")


[13.  10.4 13.4 11.  13.2]
[[18  8 10 12]
 [ 9  8 15  7]
 [19 14  7  9]
 [ 7 18 13  7]
 [11  8 18 18]]
[19 14  7  9]
[ 7 18 13  7]
This is the result from(('math', 'eng', 'crs', 'yoruba'), 4) that was compared from student3 and student4[12 -4 -6  2]


In [15]:

# Represent the scores as a 4x3 matrix, where rows = students and columns = subjects.
students=np.array([[80, 70, 90], 
                [60, 85, 75], 
                [95, 88, 92], 
                [70, 60, 65]])
print(students)



# 3.2 Total Scores per Student (Vector Addition) 
# Compute the total score for each student by summing across the row vector. 
student_1= [80 + 70 + 90]
print(f" This is the sum score for student_1 {student_1}")

student_2= [60 + 85 + 75]
print(f" This is the sum score for student_2 {student_2}")

student_3= [95 + 88 + 92]
print(f" This is the sum score for student_3 {student_3}")

student_4= [70 + 60 + 65]
print(f" This is the sum score for student_4 {student_4}")



[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]
 This is the sum score for student_1 [240]
 This is the sum score for student_2 [220]
 This is the sum score for student_3 [275]
 This is the sum score for student_4 [195]


In [31]:
# 3.3 Applying Weights (Scalar Multiplication) 
# Apply subject weights (e.g., Math is twice as important as others) using scalar 
# multiplication
scalar_mult=[2, 1, 1]
row_1=(2 *students[0,:])
print(f"The scalar weight for math is {row_1}")

row_2=(1 * students[1,:])
print(f"The scalar weight for eng is {row_2}")

row_3=(1 * students[2,:])
print(f" The scalar weight for french is {row_3}")

The scalar weight for math is [160 140 180]
The scalar weight for eng is [60 85 75]
 The scalar weight for french is [95 88 92]


In [30]:
# 3.4 Average Score per Subject (Matrix Operations) 
# Compute the average score for each subject by calculating the column-wise mean.
average_score_per_subject=np.mean(students[:,0])
print(average_score_per_subject)
average_score_per_subject=np.mean(students[:,1])
print(average_score_per_subject)
average_score_per_subject=np.mean(students[:,2])
print(average_score_per_subject)
average_score_per_subject=np.mean(students, axis=0)
print(average_score_per_subject)

76.25
75.75
80.5
[76.25 75.75 80.5 ]


In [34]:
#3.5 Final Grades using Matrix Multiplication 
# Use matrix multiplication with a weight vector (e.g., [0.5, 0.3, 0.2]) to calculate final grades.
weight_vector=[0.5, 0.3, 0.2]
final_grade=np.dot(students, weight_vector)
print(f"This are the final grades of students {final_grade}")

This are the final grades of students [79.  70.5 92.3 66. ]


In [35]:
# 3.6 Comparing Students (Vector Subtraction) 
# Compare two students’ performances by subtracting their score vectors.
compared_result=np.subtract(student3, student4)
print(compared_result)

[12 -4 -6  2]
